version: '3.2'

services:
    web:
        build: .
        environment:
            - PORT
            - NODE_ENV
            - REDIS_URL
            - CACHE_SECONDS
        ports:
            - target: ${PORT}
              published: ${PORT}
        links:
            - redis
        depends_on:
            - redis

    redis:
        image: redis
