version: '3.2'

services:
    web:
        build: .
        volumes:
            - .:/app
        environment:
            - PORT
            - NODE_ENV
        ports:
            - target: ${PORT}
              published: ${PORT}
        command: npx nodemon server --ignore transposed
