version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    links:
      - redis
    depends_on:
      - redis
    command: npm run local
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis
      - CACHE_SECONDS=1

  redis:
    image: redis
